enum Permissions {
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_DEACTIVATE = 'USER_DEACTIVATE',
  USER_ADD_PERMISSION = 'USER_ADD_PERMISSION',
  USER_REMOVE_PERMISSION = 'USER_REMOVE_PERMISSION',
  USER_GET_DETAILS = 'USER_GET_DETAILS',
  PERMISSION_CREATE = 'PERMISSION_CREATE',
  PERMISSION_LIST = 'PERMISSION_LIST',
  PERMISSION_GET_DETAILS = 'PERMISSION_GET_DETAILS',
  PERMISSION_DELETE = 'PERMISSION_DELETE',
  ALERT_CREATE = 'ALERT_CREATE',
  ALERT_UPDATE = 'ALERT_UPDATE',
  ALERT_DELETE = 'ALERT_DELETE',
  ALERT_DEACTIVATE = 'ALERT_DEACTIVATE',
}

export default Permissions;
